development:
  adapter: postgresql
  database: twatter_development
  username: development
  password: development

test:
  adapter: postgresql
  database: twatter_test
  username: test
  password: test

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
