development:
  adapter: postgresql
  database: twatter_development
  username: development
  password: development

test:
  adapter: postgresql
  database: twatter_test
  username: test
  password: test
